sudo: required
services:
  - docker
before_script:
  - env >> .env
script:
  - docker build -t noneuser2183/go-rest .
  - echo "$docpass" | docker login -u "$docid" --password-stdin
  - docker push noneuser2183/go-rest
